In [21]:
#importar librerias
import pandas as pd
import numpy as np

In [22]:
#leer dataset
df = pd.read_csv('/content/Performance_of_Stuednts.csv')

In [23]:
#primeras filas
df.head()

,gender,race/group,parental education level,lunch,test prep course,math score,science score,english score
0,Female,Group 10,bachelor's degree,standard,none,66,72,74
1,Female,Group 20,some college,standard,completed,69,90,88
2,Female,Group 10,master's degree,standard,none,90,88,93
3,Male,Group 9,associate's degree,free/reduced,none,47,57,44
4,Male,Group 20,some college,standard,none,76,44,75

In [26]:
#mostrar columnas del dataset
df.columns

Index(['gender', 'race/group', 'parental education level', 'lunch',
       'test prep course', 'math score', 'science score', 'english score'],
      dtype='object')

In [25]:
#muestra cantidad filas y columnas
df.shape

(1000, 8)

In [32]:
"""
cuando identifiquemos columnas categoricas, debemos observar la
cantidad de categorias de dicha columna.
"""
df['parental education level'].value_counts()#muestra carpetas categoricas y distribucion

parental education level
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [33]:
df['parental education level'].value_counts().count()# muestra el numero

np.int64(6)

In [34]:
#estadistica en variables numericas
df.describe().round()

       math score  science score  english score
count      1000.0         1000.0         1000.0
mean         66.0           69.0           68.0
std          15.0           15.0           15.0
min           0.0           17.0           10.0
25%          57.0           59.0           58.0
50%          66.0           70.0           69.0
75%          77.0           79.0           79.0
max         100.0          100.0          100.0

In [35]:
df.info()# mostrara tipos de datos y nulos en el dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gender                    1000 non-null   object
 1   race/group                1000 non-null   object
 2   parental education level  1000 non-null   object
 3   lunch                     1000 non-null   object
 4   test prep course          1000 non-null   object
 5   math score                1000 non-null   int64
 6   science score             1000 non-null   int64
 7   english score             1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [36]:
df.isnull().sum()#mostrara la cantidad de nulos por columnas

gender                      0
race/group                  0
parental education level    0
lunch                       0
test prep course            0
math score                  0
science score               0
english score               0
dtype: int64

In [37]:
df_limpio = df.dropna() # borramos nulos

In [ ]:
df_limpio.to_csv("nuevo_csv_limpioi")